# Generated by Django 4.2.6 on 2023-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_id_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Сумма оплаты'),
        ),
    ]
