# Generated by Django 4.2.6 on 2023-11-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_course_amount_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Сумма оплаты'),
        ),
    ]
