# Generated by Django 4.2.6 on 2023-11-13 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_subscription_sub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
